### ISSUE TITLE
Can't run any of these sketches using the latest version of Processing.

### ISSUE THREAD

**Issue by arashsa** [tsulej/GenerateMe#2]
There seems to be some errors running this using the latest version of Processing. Maybe include which version the scripts can run in? Or maybe someone can upgrade these to work with the latest version? The issue seems to be with setting the size of the canvas/window.

**Comment by tsulej** [comment]
Just run it on Processing 2. You can have both versions of Processing on your computer. I've made an attempt to upgrade scripts for new Processing but it's too much effort (however only few things are need to be changed) to make it on all scripts. Processing 3 do not introduce anything new or interesting from my perspective. So sorry for that, I stay with version 2.

**Comment by tsulej** [comment]
just an additional note - it's not only windows size but also the place where image is drawn.
