### ISSUE TITLE
Analog TV Filter

### ISSUE THREAD

**Issue by empsmoke** [tsulej/GenerateMe#7]
Dear Tsulej,
Do you have the C++ version of the analog TV filter?
I really hope that would be useful.

**Comment by tsulej** [comment]
C code is in source of XScreenSaver:
https://www.jwz.org/xscreensaver/download.html

Java code is packed inside 
https://github.com/tsulej/GenerateMe/blob/master/ntsc_analogtv/code/GenerateMeLibs.jar

**Comment by empsmoke** [comment]
How do I compile it? Console or Desktop?

**Comment by tsulej** [comment]
For C code - follow XScreenSaver compilation rules (As I remember it's typical autoconf/automake setup)
for Java - whatever you want (console, eclipse, processing).
